### ISSUE TITLE
Version >= 2.2.1 might cause backpressure changes

### ISSUE THREAD

**Issue by ostrolucky** [amphp/amp#291] opened 2019-11-17 14:24 UTC
I just noticed that my tests with [lowest dependencies](https://circleci.com/gh/ostrolucky/stdinho/257) are much quicker than [regular one](https://circleci.com/gh/ostrolucky/stdinho/256) and troubleshooted this to amp 2.3.0.

**Comment by kelunik** [comment] 2019-11-17 15:05
These builds aren't public, so we can't look at them, they just return a 404.

**Comment by ostrolucky** [comment] 2019-11-17 15:07
Oh sorry, didn't realize. Anyways, project is https://github.com/ostrolucky/stdinho, shouldd be easy to reproduce locally just by changing amphp/amp version

**Comment by kelunik** [comment] 2019-11-17 18:11
amphp/amp @ 2.2.x shows the same behavior for me.

**Comment by ostrolucky** [comment] 2019-11-17 18:15
```
➜  stdinho git:(master) ✗ git rev-parse HEAD
c37d0aa0529d4698b8f1d442a0b48c25aafd5bc1
➜  stdinho git:(master) ✗ composer show amphp/amp | grep version
versions : * v2.2.0
➜  stdinho git:(master) ✗ ./vendor/bin/phpunit
PHPUnit 8.4.3 by Sebastian Bergmann and contributors.

....                                                                4 / 4 (100%)

Time: 528 ms, Memory: 10.00 MB

OK (4 tests, 10 assertions)
➜  stdinho git:(master) ✗ composer require amphp/amp:2.3.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating amphp/amp (v2.2.0 => v2.3.0): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
➜  stdinho git:(master) ✗ ./vendor/bin/phpunit
PHPUnit 8.4.3 by Sebastian Bergmann and contributors.

....                                                                4 / 4 (100%)

Time: 20.51 seconds, Memory: 10.00 MB

OK (4 tests, 10 assertions)
```

**Comment by kelunik** [comment] 2019-11-17 19:46
Indeed, 2.2.0 runs fast, but 2.2.1 runs slow. https://github.com/amphp/amp/compare/v2.2.0...v2.2.1#diff-75af369ed66c35ef857072a2f0733cc1 is the only change there.

**Comment by kelunik** [comment] 2019-11-17 20:20
Yup, c45cd5a is the cause for this.

**Comment by trowski** [comment] 2019-11-18 03:53
@kelunik That seems odd, what's happening that causes it to slow down? The [next commit](a726db92a5624ffa1166f70ea27d38e83e1d779c) removed some of the code added there and should result in *fewer* back-pressure promises.

**Comment by ostrolucky** [comment] 2020-01-31 20:42
Any news?

**Comment by kelunik** [comment] 2020-01-31 23:28
Nope, sorry.

**Comment by kelunik** [comment] 2021-12-03 00:12
I'm closing this, as there hasn't been any other interest in this issue nor any activity.

**Closed by kelunik** 2021-12-03 00:12 UTC
