### ISSUE TITLE
In production, \Amp\Promise\some() allows you to pass Deferred instances to it.

### ISSUE THREAD

**Issue by far-blue** [amphp/amp#156] opened 2017-08-30 10:50 UTC
In dev mode, \Amp\Promise\some() doesn't allow Deferred instances but in live mode, Deferred is optimised to a Promise and so some() doesn't throw an error. This is a change in behaviour between dev and live which shouldn't exist.

**Comment by bwoebi** [comment] 2017-08-30 12:00
It is like there were an assertion in `\Amp\Promise\some()`: `assert(!$promise instanceof \Amp\Deferred)`. As assertions are off in production, it obviously allows you to do it in production. But that's inherent to the nature of assertions, if you turn them off.

If you want to be strict in production, then, obviously, turn the assertions active and set `zend.assertions=1` in your ini.

**Comment by kelunik** [comment] 2017-08-30 12:50
Duplicate of #155.

It's documented here: https://amphp.org/amp/promises/#promise-creation

**Closed by kelunik** 2017-08-30 12:50 UTC
