### ISSUE TITLE
Tracing watchers

### ISSUE THREAD

**Issue by brstgt** [amphp/amp#195] opened 2017-12-20 07:50 UTC
Similar to tracing double resolution of promises, it is very helpful to trace watchers.
This can e.g. help a lot in situations where the loop does not cleanly shut down because of lingering watchers. Sometimes this is even required in production as an issue cannot be pinpointed in a dev environment. I already used that in production and would love to have that as an official functionality.

1. Why do I need assertions enabled for that? They add more performance penalty, right? if (AMP_DEBUG...) without an assertion shouldn't really harm performance.
2. It would be great to have a finer control about tracing, especially when enabling that in prod
3. Why does that require a const? Having that as a runtime var would enable us to enable/disable tracing on a running process. Also very helpful in production envs.

E.g. how about:
```
AMP_TRACE_PROMISE_RESOLUTION // What the name says
AMP_TRACE_WATCHER // What the name says
AMP_TRACE_LIMIT // Limiting traces to $limit levels. Helps to save performance in prod env. ```
```
Mostly the last couple of BT steps are enough

As runtime vars this _could_ be done through a static config class:
```
\Amp\Trace::enablePromiseResolution()
\Amp\Trace::disablePromiseResolution()
...
```
or even as a loop-state-config.

Any thoughts?

**Comment by kelunik** [comment] 2017-12-20 08:01
Duplicate of #165. There's a PoC implementation in https://github.com/amphp/amp/commits/debug-coroutine

**Closed by kelunik** 2017-12-20 08:01 UTC
